"""LaTeX reproducibility-appendix snippet, ready to paste into a paper."""

from __future__ import annotations

from ..engine import CheckResult
from ..rules.base import Status


def _escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for char, escaped in replacements.items():
        text = text.replace(char, escaped)
    return text


def render(result: CheckResult) -> str:
    card = result.card
    lines: list[str] = []
    lines.append("% Reproducibility appendix (generated by adduce; edit before submission)")
    lines.append(r"\section*{Reproducibility}")
    lines.append("")
    frameworks = ", ".join(sorted(result.repo.frameworks.detected - {"python"})) or "Python"
    lines.append(
        _escape(
            f"Our implementation uses {frameworks}. "
            "The repository provides the following reproducibility artifacts:"
        )
    )
    lines.append(r"\begin{itemize}")
    for cat in card.categories:
        passed = [f for f in cat.findings if f.status is Status.PASS and not f.suppressed]
        for finding in passed:
            lines.append(r"  \item " + _escape(f"{finding.title}: {finding.message}"))
    lines.append(r"\end{itemize}")

    gaps = [
        f
        for f in card.findings
        if f.status in (Status.PARTIAL, Status.FAIL) and not f.suppressed
    ]
    if gaps:
        lines.append("")
        lines.append("% Known gaps at generation time -- resolve or disclose:")
        for finding in gaps:
            lines.append(f"% - {finding.rule_id}: {finding.message}")
    lines.append("")
    return "\n".join(lines)
