"""LaTeX reproducibility-appendix snippet, ready to paste into a paper."""

from __future__ import annotations

from ..engine import CheckResult
from ..rules.base import Finding, Status, summarize_items

_STATUS_LABEL = {
    Status.PASS: "pass",
    Status.PARTIAL: "partial",
    Status.FAIL: "fail",
    Status.NOT_APPLICABLE: "n/a",
    Status.UNKNOWN: "unknown",
}


def _item_census(finding: Finding) -> str:
    """The complete child count and its per-status split, or nothing.

    Summarised rather than listed, matching ``markdown`` and ``terminal``: no
    child appears here, so this line cannot be mistaken for the whole set.
    """
    if not finding.items:
        return ""
    counts = summarize_items(finding.items)
    split = ", ".join(
        f"{count} {_STATUS_LABEL[status]}" for status, count in counts.items() if count
    )
    return f"{len(finding.items)} item(s) not listed here: {split}"


def _escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for char, escaped in replacements.items():
        text = text.replace(char, escaped)
    return text


def render(result: CheckResult) -> str:
    card = result.card
    lines: list[str] = []
    lines.append("% Reproducibility appendix (generated by adduce; edit before submission)")
    lines.append(r"\section*{Reproducibility}")
    lines.append("")
    frameworks = ", ".join(sorted(result.repo.frameworks.detected - {"python"})) or "Python"
    lines.append(
        _escape(
            f"Our implementation uses {frameworks}. "
            "The repository provides the following reproducibility artifacts:"
        )
    )
    lines.append(r"\begin{itemize}")
    for cat in card.categories:
        passed = [f for f in cat.findings if f.status is Status.PASS and not f.suppressed]
        for finding in passed:
            text = f"{finding.title}: {finding.message}"
            census = _item_census(finding)
            if census:
                text += f" -- {census}"
            lines.append(r"  \item " + _escape(text))
    lines.append(r"\end{itemize}")

    gaps = [
        f
        for f in card.findings
        if f.status in (Status.PARTIAL, Status.FAIL)
    ]
    if gaps:
        lines.append("")
        lines.append("% Known gaps at generation time -- resolve or disclose:")
        for finding in gaps:
            suffix = " (ignored by policy; observed status retained)" if finding.suppressed else ""
            census = _item_census(finding)
            if census:
                suffix += f" -- {census}"
            lines.append(f"% - {finding.rule_id}: {finding.message}{suffix}")
    lines.append("")
    return "\n".join(lines)
